server:
  port: 9999


spring:
  thymeleaf:
    suffix: .html
    content-type: text/html
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/




redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  pool:
    max-total: 1000
    max-wait: 500
    max-idel: 100
  timeout: 10

#

pagehelper:
  auto-dialect:
  reasonable:  true
  support-methods-arguments:  true
  params: count=countSql
  dialect: mysql
