
@startuml




start

:"注册功能逻辑";
start
:"输入手机号";
:"输入密码";
:"……";


if("执行插入") then (true)

    :转到登陆;
    :输入手机号&&输入密码;
    if ("执行登陆查询") then (true)
        if("判断是否绑定学生") then(No)
           :"已绑定,跳转到主页";
        else
           :"如果没绑定，进行绑定";
           :"绑定事件添加学生信息";
                    if("绑定成功")then(true)
                        :"跳转到主页";
                    else
                        :"绑定失败，提示信息，继续绑定";








    endif

    :"顺序步骤3处理";

endif



if ("条件4判断") then (yes)

:"条件4成立的动作";

else

    if ("条件5判断") then (yes)

        :"条件5成立时的动作";

    else (no)

        :"条件5不成立时的动作";

    endif

endif

stop

@enduml
