spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/zh_education
    #url: jdbc:mysql://localhost:3306/zh_education
    password: 123456
    sql-script-encoding: utf-8
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mybatis/*.xml
#mapper-locations: "classpath:/mybatis/*.xml"
#mybatis.mapper-locations=classpath:/mapper/*Mapper.xml
