spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/zh_education
    #url: jdbc:mysql://localhost:3306/zh_education
    password: 123456
    sql-script-encoding: utf-8
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    date-format: yyyy-MM-dd
  time-zone: GMT+8
#server:
#  port: 8081
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mybatis/*.xml

